#!/bin/bash

docker run -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 \
            --network ehrbase-net \
            --name ehrdb ehrbaseorg/ehrbase-postgres:latest

while ! (docker container logs ehrdb | fgrep -q "database system is ready to accept connections");
    do sleep 1;
    echo "... waiting for keycloak ...";
done
echo "DATABASE READY"
